### PR TITLE
Python Versioning

### PR DESCRIPTION
**Pull request by Allstreamer**
Implements Equality and Ordering Operations for Python Pep-440 Versions as described in the image below:
<br>
www debuggex com_

Intergrates very nicely with @Kiwifuit's #18 Where His version requirement code can be supplemented by my system

### CODE REVIEW

**Comment by Kiwifuit** [comment]
@Allstreamer in lines 133 and 134, where are `Derivative` and `derivative` from respectively?

[Here's a link to the lines in question](https://github.com/Kiwifuit/rust-pip/blob/main/src/requirements/package_version.rs#L133-L134)

**Comment by Allstreamer** [comment]
Can you elaborate on what you mean by where

**Comment by Allstreamer** [comment]
Ah misread the question at first

**Comment by Kiwifuit** [comment]
My IDE cannot resolve lines 133 and 134 in your code for some reason

**Comment by Allstreamer** [comment]
Check main.rs & Cargo.toml. There their usage is denfined

**Comment by Allstreamer** [comment]
You forgot to include all changes In your branch

**Pull request closed without merging**
