### PR TITLE
Add branching strategy and contribution guide

### LINKED ISSUE #28: Add the branching strategy to the `README`
image

### PR DESCRIPTION
**Pull request by John15321**
Add branching strategy explanation and contributing guide for new developers on how to work on the project.

### CODE REVIEW

**Review by Allstreamer — COMMENTED** [review]
Contribution Guide should probably mention formatting for pull requests i.e.
- that the issue Number should be in the title
- summary of changes in the body of the pull
- Labels
- Milestone
- etc

**Comment by John15321** [comment]
> Contribution Guide should probably mention formatting for pull requests i.e.
> 
> * that the issue Number should be in the title
> * summary of changes in the body of the pull
> * Labels
> * Milestone
> * etc

oh yeah I forgot about that

**Comment by John15321** [comment]
> Contribution Guide should probably mention formatting for pull requests i.e.
> 
> * that the issue Number should be in the title
> * summary of changes in the body of the pull
> * Labels
> * Milestone
> * etc

Okay I added some, I wont be making it too detailed like cmon

**Review by DevChaudhary78 — APPROVED** [review]
`CONTRIBUTING.md` is very descriptive, short as well as long versions are appreciated, approving this. 👍

**Comment by John15321** [comment]
> `CONTRIBUTING.md` is very descriptive, short as well as long versions are appreciated, approving this. 👍

You shouldn't merge it yourself, the author of the PR does the merge, not to mention that you should have waited for everyone's approve

**Comment by DevChaudhary78** [comment]
> 

Ohh okay my bad, I will make a note of this next time sorry 👍

**Pull request merged**
