### PR TITLE
Switch arg parsing to clap-derive + small cargo refactor

### PR DESCRIPTION
**Pull request by tranzystorekk**
- switch arg parsing to clap-derive
- include Cargo.lock file

these small changes should nudge the project in a nice direction 😄

### CODE REVIEW

**Comment by John15321** [comment]
@tranzystorek-io hi could you just change the target branch to be `develop`? :) We will merge it downstream later

**Comment by John15321** [comment]
@tranzystorek-io looks good. But some reason I cannot allow the CI to run on this PR :/ Im not sure how to do that

**Review by John15321 — APPROVED** [review]

**Comment by tranzystorekk** [comment]
@John15321 probably missing `on: pull_request` in workflow file

**Comment by John15321** [comment]
> @John15321 probably missing `on: pull_request` in the workflow file

You are right! I somehow forgot about that. Thanks. I will create an issue for that and add it. Then rebase your branch, then the CI should run and we can merge your changes 😄

**Comment by John15321** [comment]
@tranzystorek-io could you rebase the branch now?

**Comment by John15321** [comment]
@tranzystorek-io I know that this issue was present before your pr but could you please fix the issues present in the `Code check` job?

**Pull request merged**
