### PR TITLE
Add strategy matrix for toolchain and different OSs with caching

### LINKED ISSUE #29: Add macOS and windows testing in the CI/CD piplines
Add a strategy matrix to the CI jobs for additional runs on Windows and macOS

### LINKED ISSUE #37: Add strategy matrix to the building and testing CI jobs for all three toolchain channels
Related to:
* https://github.com/John15321/rust-pip/issues/29

### PR DESCRIPTION
**Pull request by John15321**
Add strategy matrix for `ubuntu-latest`, `windows-latest`, `macos-latest` and toolchain matrix for `stable`, `beta`, `nightly`. Additionally some basic caching for the CI jobs has been added and some other misc reformats of the CI jobs

### CODE REVIEW

**Review by Allstreamer — APPROVED** [review]
Looking good!

**Review by Allstreamer — APPROVED** [review]
LGTM!

**Comment by zephaniahong** [comment]
Not too familiar with CI/CD so I'll leave the review to others.

**Review by DevChaudhary78 — COMMENTED** [review]
I went through what I know, and it seems fine to me. though I haven't gone through CI/CD, so leaving it for other reviewers. 👍

**Pull request merged**
